/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspCServletContext/1.0
 * Generated at: 2015-07-24 08:46:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lessons.RoleBasedAccessControl;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.owasp.webgoat.session.*;
import org.owasp.webgoat.lessons.RoleBasedAccessControl.RoleBasedAccessControl;

public final class EditProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	WebSession webSession = ((WebSession)session.getAttribute("websession"));
	Employee employee = (Employee) session.getAttribute("RoleBasedAccessControl.Employee");

      out.write("\r\n\t\t<div class=\"lesson_title_box\"><strong>Welcome Back </strong><span class=\"lesson_text_db\">");
      out.print(webSession.getUserNameInLesson());
      out.write("</span> - Edit Profile Page</div>\r\n\t\t<div class=\"lesson_text\">\r\n\t\t\t<form id=\"form1\" name=\"form1\" method=\"post\" action=\"");
      out.print(webSession.getCurrentLesson().getFormAction());
      out.write("\">\r\n<Table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n\t\t\t\t<TR><TD width=\"110\">\r\n\t\t\t\t\t\tFirst Name:\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD width=\"193\">\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.FIRST_NAME);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getFirstName());
      out.write("\"/>\r\n\t\t\t\t  </TD>\r\n\t\t\t\t\t<TD width=\"110\">\t\t\t\t\r\n\t\t\t\t\t\tLast Name:\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD width=\"196\">\r\n\t\t\t\t\t \t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.LAST_NAME);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getLastName());
      out.write("\"/>\r\n\t\t\t\t  </TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR><TD>\t\t\t\t\r\n\t\t\t\t\t\tStreet: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.ADDRESS1);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getAddress1());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\t\t\t\t\r\n\t\t\t\t\t\tCity/State: \r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.ADDRESS2);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getAddress2());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR><TD>\r\n\t\t\t\t\t\tPhone: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.PHONE_NUMBER);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getPhoneNumber());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\t\t\t\t\r\n\t\t\t\t\t\tStart Date: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.START_DATE);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getStartDate());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR><TD>\r\n\t\t\t    \t\tSSN: \r\n\t\t\t    \t</TD>\r\n\t\t\t    \t<TD>\r\n\t\t\t    \t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.SSN);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getSsn());
      out.write("\"/> \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\t\t\t\t\r\n\t\t\t\t\t\tSalary: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.SALARY);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getSalary());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR><TD>\r\n\t\t\t\t\t\tCredit Card: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.CCN);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getCcn());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\t\t\t\t\r\n\t\t\t\t\t\tCredit Card Limit: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.CCN_LIMIT);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getCcnLimit());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR><TD>\r\n\t\t\t\t\t\tComments: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD colspan=\"3\">\r\n\t\t\t\t\t\t<input name=\"");
      out.print(RoleBasedAccessControl.DESCRIPTION);
      out.write("\" type=\"text\" class=\"lesson_text_db\" value=\"");
      out.print(employee.getPersonalDescription());
      out.write("\" size=\"58\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t<TR>\r\n\t\t\t\t\t<TD colspan=\"2\">\t\t\t\t\r\n\t\t\t\t\t\tDisciplinary Explanation:  \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\t\t\t\r\n\t\t\t\t\t\tDisc. Date:\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\t\t\t\r\n\t\t\t\t\t\t<input class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.DISCIPLINARY_DATE);
      out.write("\" type=\"text\" value=\"");
      out.print(employee.getDisciplinaryActionDate());
      out.write("\"/>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR>\r\n\t\t\t\t\t<TD colspan=\"4\">\r\n\t\t\t\t\t\t<textarea name=\"");
      out.print(RoleBasedAccessControl.DISCIPLINARY_NOTES);
      out.write("\" cols=\"53\" rows=\"2\" wrap=\"off\" class=\"lesson_text_db\" >");
      out.print(employee.getDisciplinaryActionNotes());
      out.write("</textarea>\r\n\t\t\t\t\t</TD>\r\n\t\t\t\t</TR>\r\n\t\t\t\t<TR>\t\r\n\t\t\t\t<TD>\t\t\t\t\r\n\t\t\t\t\t\tManager: \r\n\t\t\t\t\t</TD>\r\n\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t<select class=\"lesson_text_db\" name=\"");
      out.print(RoleBasedAccessControl.MANAGER);
      out.write("\">\r\n\t\t\t\t\t\t");

				      	List employees = (List) session.getAttribute("RoleBasedAccessControl.Staff");
				      	Iterator i = employees.iterator();
						while (i.hasNext())
						{
							EmployeeStub stub = (EmployeeStub) i.next();
								
      out.write("\r\n\t\t\t\t\t\t\t\t<option value=\"");
      out.print(Integer.toString(stub.getId()));
      out.write('"');
      out.write('>');
      out.print(stub.getFirstName() + " " + stub.getLastName());
      out.write("</option>\r\n\t\t\t\t\t\t");
}
      out.write("\r\n\t\t\t\t\t\t</select>\r\n\t\t\t\t\t</TD>\t\r\n\t\t\t\t</TR>\r\n\t\t\t\t</Table>\r\n\t\t\t\t<BR>\r\n\t\t\t\t<div class=\"lesson_buttons_bottom\">\r\n\t\t\t\t<table width=\"460\" height=\"20\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n               \t\t<tr>\r\n                     \t\t<td width=\"57\">\r\n\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(RoleBasedAccessControl.VIEWPROFILE_ACTION);
      out.write("\"/>\r\n\t\t\t\t  \t\t</td>\r\n\t\t\t\t  \t\t\r\n                       \t<td width=\"81\">\r\n \t\t\t\t\t\t\t<input name=\"");
      out.print(RoleBasedAccessControl.EMPLOYEE_ID);
      out.write("\" type=\"hidden\" value=\"");
      out.print(employee.getId());
      out.write("\">\r\n\t\t\t\t\t\t\t<input name=\"");
      out.print(RoleBasedAccessControl.TITLE);
      out.write("\" type=\"hidden\" value=\"");
      out.print(employee.getTitle());
      out.write("\">\r\n\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(RoleBasedAccessControl.UPDATEPROFILE_ACTION);
      out.write("\"/>\r\n\t\t\t\t\t\t</td>\r\n                        \t<td width=\"211\"></td>\r\n                        \t<td width=\"83\">\r\n\t \t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(RoleBasedAccessControl.LOGOUT_ACTION);
      out.write("\"/>\r\n\t\t\t\t\t\t</td>\r\n                 \t</tr>\r\n              \t</table>\t\t\t\r\n\t\t\t</div></form>\r\n\t\t</div>\r\n\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
