/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspCServletContext/1.0
 * Generated at: 2015-07-24 08:46:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.owasp.webgoat.session.WebSession;

public final class reportBug_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n");

	WebSession webSession = ((WebSession) session
			.getAttribute("websession"));

      out.write("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\r\n<title>WebGoat V5.4</title>\r\n<link rel=\"stylesheet\" href=\"css/webgoat.css\" type=\"text/css\" />\r\n</head>\r\n\r\n<body>\r\n\r\n<div id=\"wrap\">\r\n<div id=\"top\"></div>\r\n<div id=\"start\">\r\n<p>Thank you for taking the time to improve WebGoat!</p>\r\n<p>The lesson you were on was: ");
      out.print(webSession.getCurrentLesson().getName());
      out.write("</p>\r\n<p>There are several ways to report a bug, fix a bug, or get help.</p>\r\n\r\n<b>To report a bug:</b>\r\n<ol>\r\n\t<li>File a WebGoat defect using <a\r\n\t\thref=\"http://code.google.com/p/webgoat/issues/list\">Google Code\r\n\tWebGoat Issues</a>. Please be as specific as possible. If you have a\r\n\trecommended solution for a bug, include the solution in the bug report.</li>\r\n</ol>\r\n<b>To get help:</b>\r\n<ol>\r\n\t<li>Look in the <a\r\n\t\thref=\"http://code.google.com/p/webgoat/wiki/FAQ\">FAQ</a>, \r\n\tthe most common problems are in the FAQ. The FAQ also allows user comments,\r\n\tbut it is not monitored like the WebGoat mailing list.</li>\r\n\t<li>Send an email to the <a\r\n\t\thref=\"mailto: owasp-webgoat@lists.owasp.org?subject=WebGoat Help Request - Lesson: \r\n\t\t\t\t\t\t\t\t\t\t\t\t ");
      out.print(webSession.getCurrentLesson().getName());
      out.write("\">WebGoat\r\n\tmail list</a>. The WebGoat mail list is the preferred method to ask for\r\n\thelp. It is likely that someone has already experienced the issue you\r\n\tare seeing. In order to post to the list you must be <a\r\n\t\thref=\"https://lists.owasp.org/mailman/listinfo/owasp-webgoat\">subscribed</a>\r\n\tto the WebGoat Mail List.</li>\r\n\t<li>Send an email to <a\r\n\t\thref=\"mailto: ");
      out.print(webSession.getWebgoatContext().getFeedbackAddress());
      out.write("?subject=WebGoat Direct Help Request - Lesson: \r\n\t\t\t\t\t\t\t\t\t\t\t\t ");
      out.print(webSession.getCurrentLesson().getName());
      out.write("\">Bruce\r\n\tMayhew</a></li>\r\n</ol>\r\n<b>To fix a bug, typo, or enhance WebGoat:</b>\r\n<ol>\r\n\t<li>Send an email to <a\r\n\t\thref=\"mailto: ");
      out.print(webSession.getWebgoatContext().getFeedbackAddress());
      out.write("?subject=WebGoat Contributor Request\">Bruce\r\n\tMayhew</a>. This will start the discussion of getting you added to the <a\r\n\t\thref=\"http://code.google.com/p/webgoat/people/list\">WebGoat\r\n\tContributers List</a>. Once you become a WebGoat contributor, you can fix\r\n\tas many bugs/lessons as you desire.</li>\r\n</ol>\r\n\r\n\t\t<div id=\"bottom\">\r\n\t\t\t<div align=\"center\"><a href=\"http://www.owasp.org\">OWASP Foundation</a> | \r\n\t\t\t\t\t\t\t\t<a href=\"http://www.owasp.org/index.php/OWASP_WebGoat_Project\">Project WebGoat</a> \r\n\t\t\t</div>\r\n\t  \t</div>\r\n\r\n</div>\r\n</div>\r\n</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
